repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: setup.cfg
      - id: check-added-large-files
        exclude: data
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: fix-byte-order-marker
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude: poetry.lock
        args:
          - --ignore-words=.dictionary.txt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff-format
        args: [--preview, -s]
      - id: ruff
        args: [--fix]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        exclude: setup.cfg
